version: '3.4'

networks:
  aspnetcoreapp:
    driver: bridge

services:
  web:
    build:
      context: .
    ports:
      - "56133:80"
      - "44327:443"
    depends_on: 
      - "database"
    networks:
      - aspnetcoreapp

  database:
    build: ./database
    ports:
      - "1344:1433"
    networks:
      - aspnetcoreapp
